django_intro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls'))
]

petstagram/accounts/urls.py
from django.urls import path, include

from accounts import views

app_name = 'accounts'

profile_patterns = [
        path('', views.profile_details, name='profile_details'),
        path('edit/', views.profile_edit, name='profile_edit'),
        path('delete/', views.profile_delete, name='profile_delete'),
]

authentication_patterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
]

urlpatterns = [
    path('', include(authentication_patterns)),
    path('profile/<int:pk>', include(profile_patterns))
]

petstagram/common/urls.py
from django.urls import path

from common import views

app_name = 'common'

urlpatterns = [
    path('', views.home_page, name='home'),

]

petstagram/pets/urls.py
from django.urls import path, include
from pets import views

app_name = 'pets'
urlpatterns = [
    path('add/', views.pet_add, name='add'),
    path('<str:username>/pet/<slug:pet_slug>', include([
        path('', views.pet_details, name='details'),
        path('edit/', views.pet_edit, name='edit'),
        path('delete/', views.pet_delete, name='delete'),
    ]))
]

petstagram/photos/urls.py
from django.urls import path, include

from photos import views

app_name = 'photos'

urlpatterns = [
    path('', views.photo_add, name='add'),
    path('<int:pk>', include([
        path('', views.photo_details, name='details'),
        path('edit/', views.photo_edit, name='edit'),
    ]))
]

tasks/urls.py
from django.urls import path
from tasks import views

urlpatterns = [
    path('', views.index)
]

petstagram/accounts/models.py
from django.db import models

# Create your models here.

petstagram/common/models.py
from django.contrib.auth.models import User
from django.db import models

from photos.models import Photo


# Create your models here.

class Model(models.Model):
    text = models.CharField(max_length=300)
    date_and_time_of_publication = models.DateTimeField(auto_now_add=True)
    to_photo = models.ForeignKey(Photo, on_delete=models.CASCADE)

class Like(models.Model):
    to_photo = models.ForeignKey(Photo, on_delete=models.CASCADE)

petstagram/pets/models.py
from django.db import models
from django.utils.text import slugify


# Create your models here.

class Pet(models.Model):
    name = models.CharField(max_length=30)
    personal_photo = models.URLField()
    date_of_birth = models.DateField(blank=True, null=True)
    slug = models.SlugField(unique=True, null=False, blank=True, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(f"{self.name}-{self.pk}")
        super().save(*args, **kwargs)

petstagram/photos/models.py
from django.core.validators import FileExtensionValidator, MinLengthValidator
from django.db import models

from pets.models import Pet
from photos.validators import FileSizeValidator


# Create your models here.
class Photo(models.Model):
    photo = models.ImageField(validators=[FileSizeValidator(5)])
    description = models.CharField(max_length=100, validators=[MinLengthValidator(10)], null=True, blank=True)
    location = models.CharField(max_length=30)
    tagged_pets = models.ManyToManyField(Pet, blank=True)
    date_of_publication = models.DateField(auto_now=True)

petstagram/accounts/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

# Create your views here.

def register(request: HttpRequest) -> HttpResponse:
    return render(request, 'accounts/register-page.html')

def login(request: HttpRequest) -> HttpResponse:
    return render(request, 'accounts/login-page.html')

def profile_details(request: HttpRequest, pk:int) -> HttpResponse:
    return render(request, 'accounts/profile-details-page.html')

def profile_edit(request: HttpRequest, pk:int) -> HttpResponse:
    return render(request, 'accounts/profile-edit-page.html')

def profile_delete(request: HttpRequest, pk:int) -> HttpResponse:
    return render(request, 'accounts/profile-delete-page.html')

petstagram/common/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

# Create your views here.

def home_page(request: HttpRequest) -> HttpResponse:
    return render(request, 'common/home-page.html')

petstagram/pets/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

# Create your views here.

def pet_add(request: HttpRequest) -> HttpResponse:
    return render(request, 'pets/pet-add-page.html')

def pet_details(request: HttpRequest, pk:int) -> HttpResponse:
    return render(request, 'pets/pet-details-page.html')

def pet_edit(request: HttpRequest, pk:int) -> HttpResponse:
    return render(request, 'pets/pet-edit-page.html')

def pet_delete(request: HttpRequest, pk:int) -> HttpResponse:
    return render(request, 'pets/pet-delete-page.html')

petstagram/photos/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

# Create your views here.

def photo_add(request: HttpRequest) -> HttpResponse:
    return render(request, 'photos/photo-add-page.html')

def photo_details(request: HttpRequest, pk:int) -> HttpResponse:
    return render(request, 'photos/photo-details-page.html')

def photo_edit(request: HttpRequest, pk:int) -> HttpResponse:
    return render(request, 'photos/photo-edit-page.html')

petstagram/templates/shared/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}">
    <title>Petstagram</title>
</head>

<body>

<header>
    {% include 'shared/nav.html' %}
</header>
<!-- End Header Section with Navigation Bar -->
<!-- Starts Main Section -->
<main>

    {% block content %}
    {% endblock %}
</main>

<div class="footer">
    {% include 'shared/footer.html' %}
</div>


</body>
</html>

petstagram/templates/shared/footer.html
		<span class="footer-section">
			©  SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>

petstagram/templates/shared/nav.html
{% load static %}
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="{% url 'common:home' %}">
                    <img width="50px" src="{% static '/images/free-30-instagram-stories-icons23_122570.png' %}" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="{% url 'common:home' %}">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">

                        <!-- Link to Add Pet Page -->
                        <a href="{% url 'pets:add' %}">
                            <i>Add Pet</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Add Photo Page -->
                        <a href="{% url 'photos:add' %}">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Login Page -->
                        <a href="{% url 'accounts:login' %}">
                            <i>Login</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Register Page -->
                        <a href="{% url 'accounts:register' %}">
                            <i>Register</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Lpg out -->
                        <a href="#">
                            <i>Log out</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>