django_intro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls'))
]

exercise_urls_views/destination/urls.py
from django.urls import path, include

from destination.views import index, destinations_list, destination_detail, redirect_home

app_name = 'destination'

urlpatterns = [
    path('', index, name='index'),

    path('redirect-home/', redirect_home, name='redirect_home'),
    path('destinations/', include([
        path('', destinations_list, name='list'),

        path('detail/<slug:slug>/', destination_detail, name='detail'),
    ]))

]

exercise_urls_views/review/urls.py
from django.urls import path, re_path

from review.views import recent_reviews, review_detail, reviews_by_year

app_name = 'review'
urlpatterns = [
    path('', recent_reviews, name='list'),

    re_path(r'^(?P<year>20\d{2})/$', reviews_by_year, name='list-year'),
    path('details/<int:pk>/', review_detail, name='detail'),
]

forum_app/forum_app/urls.py
from django.contrib import admin
from django.urls import path, include

import posts
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('posts.urls')),
]

petstagram/petstagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('photos/', include('photos.urls')),
    path('pets/', include('pets.urls')),

]

tasks/urls.py
from django.urls import path
from tasks import views

urlpatterns = [
    path('', views.index)
]

exercise_urls_views/common/models.py
from django.db import models

# Create your models here.

class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

exercise_urls_views/destination/models.py
from django.db import models
from django.template.defaultfilters import slugify

from common.models import TimeStampModel


# Create your models here.

class Destination(TimeStampModel):
    name = models.CharField(max_length=100, unique=True)
    slug = models.CharField(max_length=100, unique=True, blank=True)
    description = models.TextField()
    country = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.name and self.country:
            self.slug = slugify(f"{self.name} - {self.country}")
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.name} - {self.country}"

exercise_urls_views/review/models.py
from django.db import models

from common.models import TimeStampModel
from destination.models import Destination


class Review(TimeStampModel):
    author = models.CharField(max_length=100)
    body = models.TextField()
    rating = models.DecimalField(max_digits=4, decimal_places=2)
    # created_at = models.DateTimeField(auto_now_add=True)
    destination = models.ForeignKey("destination.Destination", on_delete=models.CASCADE, related_name="reviews")
    is_published = models.BooleanField(default=True)

exercise_urls_views/destination/views.py
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect

from destination.models import Destination


# Create your views here.

def index(request: HttpRequest) -> HttpResponse:
    return render(request, 'index.html')

def destinations_list(request: HttpRequest) -> HttpResponse:
    destinations = Destination.objects.all()

    context = {
        'destinations': destinations,
        'page_title': 'All Destinations'
    }

    return render(request, 'destination/list.html', context)

def destination_detail(request: HttpRequest, slug: str) -> HttpResponse:
    destination = get_object_or_404(Destination, slug=slug)

    context = {
        'destination': destination,
        'page_title': f'{destination.name} Details',
    }

    return render(request, 'destination/detail.html', context)

def redirect_home(request: HttpRequest) -> HttpResponse:
    return redirect('destination:list')

exercise_urls_views/review/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404

from review.models import Review


# Create your views here.

DEFAULT_REVIEW_COUNT = 5

def recent_reviews(request: HttpRequest) -> HttpResponse:

    review_count = request.GET.get(key='review_count', default=DEFAULT_REVIEW_COUNT)
    reviews = Review.objects.filter(is_published= True).order_by('-created_at')[:int(review_count)]

    context = {
        'reviews': reviews,
        'page_title': 'Recent Reviews',

    }

    return render(request, 'review/list.html', context)

def review_detail(request: HttpRequest, pk: int) -> HttpResponse:

    review = get_object_or_404(Review, pk=pk)

    context = {
        'review': review,
        'page_title': f'{review.author}\'s reviews on {review.destination.name}',
    }

    return render(request, 'review/detail.html', context)

def reviews_by_year(request: HttpRequest, year: int) -> HttpResponse:
    reviews = Review.objects.filter(created_at__year=year)
    context = {
        'reviews': reviews,
        'page_title': f'Reviews for {year}',
    }

    return render(request, 'review/list.html', context)

exercise_urls_views/templates/destination/detail.html
{% extends 'base.html' %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">{{ destination.name }}</h1>
            <p class="card-text">Description: {{ destination.description }}</p>
            <p class="card-text">Country: {{ destination.country }}</p>
            <p class="card-text"><small class="text-muted">Created at: {{ destination.created_at }}</small></p>
        </div>
    </div>

    <div class="mt-4">
        <a href="{% url 'review:list' %}" class="btn btn-primary">View reviews</a>
        <a href="{% url 'destination:list' %}" class="btn btn-secondary">Back to destinations</a>
    </div>
{% endblock %}

exercise_urls_views/templates/destination/list.html
{% extends 'base.html' %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <h1 class="mb-4">{{ page_title }}</h1>

    <div class="list-group">
        {% for destination in destinations %}
            <a href="{% url 'destination:detail' destination.slug %}" class="list-group-item list-group-item-action">
                {{ destination.name }} - ({{ destination.country }})
            </a>
        {% empty %}
            <p class="list-group-item">No destinations found.</p>
        {% endfor %}
    </div>
{% endblock %}